apiVersion: v1
kind: Service
metadata:
  name: {{ template "release.name" . }}
  labels:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "chart.name_version" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: serviceport
      protocol: TCP
      targetPort: serviceport
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}